# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Go@0
  inputs:
    command: 'get'
    arguments: 'github.com/go-redis/redis'
- task: Go@0
  inputs:
    command: 'build'
    workingDirectory: '$(System.DefaultWorkingDirectory)/src'
    arguments: " -o $(Build.ArtifactStagingDirectory)/redis-probe-linux "

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
    
- task: Docker@2
  displayName: Login to DockerHub
  inputs:
    command: login
    containerRegistry: DockerHubSilval

- task: Docker@2
  inputs:
    containerRegistry: 'DockerHubSilval'
    repository: 'silval/redis-probe'
    command: 'buildAndPush'
    tags: |
      latest
      $(Build.BuildId)
    Dockerfile: '$(System.DefaultWorkingDirectory)/docker/Dockerfile'
    buildContext: '$(Build.ArtifactStagingDirectory)'        
