resources:
  # Sample Go app in a GitRepo
  - name: go_repo
    type: GitRepo
    configuration:
      path: lsilvapvt/redis-probe
      branches:
        include: master
      gitProvider: acme_co_github

  # Build info for the published Go app
  - name: go_buildinfo
    type: BuildInfo
    configuration:
      sourceArtifactory: acme_co_artifactory
  # Build info for the staging promoted Go app
  - name: go_stage_buildinfo
    type: BuildInfo
    configuration:
      sourceArtifactory: acme_co_artifactory
  # Build info for the production promoted Go app
  - name: go_prod_buildinfo
    type: BuildInfo
    configuration:
      sourceArtifactory: acme_co_artifactory

pipelines:
  - name: go_redis_probe_build
    configuration:
      runtime:
        type: image
        image:
          auto:
            language: go
            versions:
              - "1.14.4"      
    steps:
      - name: redis_probe
        type: GoBuild
        configuration:
          sourceLocation: ./src
          resolverRepo: go-virtual
          noRegistry: true
          inputResources:
            - name: go_repo
          integrations:
            - name: acme_co_artifactory

      # Publish the Go sample app binary to Artifactory. Docs at https://www.jfrog.com/confluence/display/JFROG/GoPublishBinary
      - name: publish_go_binary
        type: GoPublishBinary
        configuration:
          inputSteps:
            - name: redis_probe
          targetRepository: go-local/redis-probe-files/${run_number}/redis-probe-linux
          integrations:
            - name: acme_co_artifactory

      # Publish the Go sample app build info. Docs at https://www.jfrog.com/confluence/display/JFROG/PublishBuildInfo
      - name: publish_build
        type: PublishBuildInfo
        configuration:
          inputSteps:
            - name: publish_go_binary
          outputResources:
            - name: go_buildinfo
        execution:
          onStart:
            - write_output go_buildinfo tested=false

  - name: go_redis_probe_test_promote
    steps:
      - name: func_test_1
        type: Bash
        configuration:
          integrations:
            - name: acme_co_artifactory
          inputResources:
            - name: go_buildinfo
        execution:
          onStart:
            - echo "Your pre-test1 scripts are invoked here"
            #- jfrog rt dl prod-go-local/app
            #- ls -latr
          onExecute:
            - echo "Build name= ${res_go_buildinfo_buildName}"
            - echo "Build number= ${res_go_buildinfo_buildNumber}"
            - echo "Your test 1 scripts are invoked here."

      - name: func_test_2
        type: Bash
        configuration:
          integrations:
            - name: acme_co_artifactory
          inputResources:
            - name: go_buildinfo
        execution:
          onExecute:
            - echo "Build name= ${res_go_buildinfo_buildName}"
            - echo "Build number= ${res_go_buildinfo_buildNumber}"
            - echo "Your test 2 scripts are invoked here."

      - name: security_scan
        type: XrayScan
        configuration:
          inputResources:
            - name: go_buildinfo 
          inputSteps:
            - name: func_test_1
            - name: func_test_2

      - name: promote_stage
        type: PromoteBuild
        configuration:
          targetRepository: go-stage-local
          includeDependencies: true
          copy: true
          integrations:
            - name: acme_co_artifactory
          inputResources:
            - name: go_buildinfo
          outputResources:
            - name: go_stage_buildinfo
          inputSteps:
            - name: security_scan  

      - name: integration_tests
        type: Bash
        configuration:
          integrations:
            - name: acme_co_artifactory
          inputResources:
            - name: go_stage_buildinfo
          inputSteps:
            - name: promote_stage  
        execution:
          onExecute:
            - echo "Build name= ${res_go_stage_buildinfo_buildName}"
            - echo "Build number= ${res_go_stage_buildinfo_buildNumber}"
            - echo "Your test 2 scripts are invoked here."
            
      - name: promote_prod
        type: PromoteBuild
        configuration:
          targetRepository: go-prod-local
          includeDependencies: true
          copy: true
          integrations:
            - name: acme_co_artifactory
          inputResources:
            - name: go_stage_buildinfo
          outputResources:
            - name: go_prod_buildinfo
          inputSteps:
            - name: integration_tests   

