apiVersion: v1
kind: Namespace
metadata:
  name: "${REDIS_SERVER_NAMESPACE}"
---  
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redis-probe
  name: redis-probe
  namespace: "${REDIS_SERVER_NAMESPACE}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-probe
  template:
    metadata:
      labels:
        app: redis-probe
    spec:
      containers:
      - image: ${REDIS_IMAGE_NAME}:${REDIS_IMAGE_TAG}
        name: redis-probe-pod
        imagePullPolicy: Always
        command:
          - /usr/bin/redis-probe
        env:
          - name: REDIS_SERVER_ADDRESS
            value: "${REDIS_SERVER_ADDRESS}"
          - name: REDIS_SERVER_PORT
            value: "${REDIS_SERVER_PORT}"
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: redis-server
                key: password
          - name: REDIS_DATABASE
            value: "0"  
          - name: REDIS_PROBE_SERVICE_PORT
            value: "80"
---            
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: redis-probe
  name: redis-probe
  namespace: "${REDIS_SERVER_NAMESPACE}"
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: redis-probe
  type: LoadBalancer